window.CATALOGO_DEMO = Object.freeze({
    categories: [
        {
            id: "canecas-copos",
            name: "Canecas & Copos",
            shortName: "Canecas",
            description: "Opções clássicas, térmicas e criativas para todos os momentos.",
            image: "https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=900&q=86"
        },
        {
            id: "garrafas-squeezes",
            name: "Garrafas & Squeezes",
            shortName: "Garrafas",
            description: "Modelos funcionais para rotina, eventos e ações de bem-estar.",
            image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=900&q=86"
        },
        {
            id: "canetas",
            name: "Canetas",
            shortName: "Canetas",
            description: "Do essencial ao sofisticado, com diferentes acabamentos.",
            image: "https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=900&q=86"
        },
        {
            id: "agendas-cadernos",
            name: "Agendas & Cadernos",
            shortName: "Papelaria",
            description: "Produtos úteis para organização, onboarding e relacionamento.",
            image: "https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=900&q=86"
        },
        {
            id: "bolsas-mochilas",
            name: "Bolsas & Mochilas",
            shortName: "Bolsas",
            description: "Praticidade e presença de marca dentro e fora do trabalho.",
            image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=86"
        },
        {
            id: "tecnologia",
            name: "Tecnologia",
            shortName: "Tecnologia",
            description: "Acessórios que acompanham uma rotina cada vez mais conectada.",
            image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=86"
        },
        {
            id: "kits-corporativos",
            name: "Kits Corporativos",
            shortName: "Kits",
            description: "Combinações marcantes para datas especiais e boas-vindas.",
            image: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=900&q=86"
        },
        {
            id: "ecologicos",
            name: "Linha Ecológica",
            shortName: "Ecológicos",
            description: "Escolhas conscientes com materiais de menor impacto.",
            image: "https://images.unsplash.com/photo-1605600659873-d808a13e4d2a?auto=format&fit=crop&w=900&q=86"
        }
    ],
    products: [
        {
            id: "caneca-ceramica-nordic",
            name: "Caneca Cerâmica Nordic 350 ml",
            code: "CN-1042",
            category: "canecas-copos",
            image: "https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=1200&q=88",
            gallery: [
                "https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=1200&q=88",
                "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=88"
            ],
            shortDescription: "Cerâmica com acabamento fosco e design minimalista.",
            description: "Uma caneca versátil para kits corporativos, ações de relacionamento e uso diário. O acabamento fosco valoriza aplicações discretas e sofisticadas.",
            materials: "Cerâmica",
            dimensions: "350 ml · 9,2 × 8,5 cm",
            colors: ["Areia", "Preto", "Verde", "Branco"],
            personalization: "Silk, transfer ou gravação conforme a arte",
            minQuantity: "A consultar",
            tags: ["mais vendido", "escritório"],
            featured: true,
            isNew: false
        },
        {
            id: "copo-termico-urban",
            name: "Copo Térmico Urban 500 ml",
            code: "CP-2088",
            category: "canecas-copos",
            image: "https://images.unsplash.com/photo-1577937927133-66ef06acdf18?auto=format&fit=crop&w=1200&q=88",
            gallery: ["https://images.unsplash.com/photo-1577937927133-66ef06acdf18?auto=format&fit=crop&w=1200&q=88"],
            shortDescription: "Parede dupla, tampa protetora e acabamento premium.",
            description: "Copo térmico de visual contemporâneo, ideal para equipes, eventos e campanhas premium. Ajuda a conservar a temperatura por mais tempo.",
            materials: "Aço inox e polímero",
            dimensions: "500 ml · 17,8 × 8,7 cm",
            colors: ["Preto", "Inox", "Azul-marinho"],
            personalization: "Laser ou silk",
            minQuantity: "A consultar",
            tags: ["premium", "lançamento"],
            featured: true,
            isNew: true
        },
        {
            id: "garrafa-inox-flow",
            name: "Garrafa Inox Flow 600 ml",
            code: "GF-3015",
            category: "garrafas-squeezes",
            image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=1200&q=88",
            gallery: ["https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=1200&q=88"],
            shortDescription: "Garrafa resistente com tampa rosqueável e alça.",
            description: "Uma escolha funcional para campanhas esportivas, ações internas e presentes corporativos. Design limpo e excelente área para personalização.",
            materials: "Aço inox",
            dimensions: "600 ml · 25 × 7,2 cm",
            colors: ["Branco", "Preto", "Azul", "Verde"],
            personalization: "Gravação a laser",
            minQuantity: "A consultar",
            tags: ["bem-estar", "mais vendido"],
            featured: true,
            isNew: false
        },
        {
            id: "squeeze-esportiva-active",
            name: "Squeeze Esportiva Active 750 ml",
            code: "SQ-3062",
            category: "garrafas-squeezes",
            image: "https://images.unsplash.com/photo-1523362628745-0c100150b504?auto=format&fit=crop&w=1200&q=88",
            gallery: ["https://images.unsplash.com/photo-1523362628745-0c100150b504?auto=format&fit=crop&w=1200&q=88"],
            shortDescription: "Leve, prática e ideal para eventos esportivos.",
            description: "Squeeze com pegada confortável e tampa de acionamento rápido, indicada para academias, eventos e programas de qualidade de vida.",
            materials: "Polímero livre de BPA",
            dimensions: "750 ml · 26 × 7,5 cm",
            colors: ["Transparente", "Azul", "Vermelho", "Fumê"],
            personalization: "Silk em até duas cores",
            minQuantity: "A consultar",
            tags: ["esportivo"],
            featured: false,
            isNew: false
        },
        {
            id: "caneta-metal-signature",
            name: "Caneta Metal Signature",
            code: "CA-4120",
            category: "canetas",
            image: "https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=1200&q=88",
            gallery: ["https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=1200&q=88"],
            shortDescription: "Traço macio, corpo metálico e acabamento elegante.",
            description: "Caneta executiva com visual sóbrio e ótima percepção de valor, indicada para eventos, reuniões, kits de boas-vindas e presentes institucionais.",
            materials: "Alumínio",
            dimensions: "14 × 1,1 cm",
            colors: ["Preto", "Grafite", "Azul", "Dourado"],
            personalization: "Laser",
            minQuantity: "A consultar",
            tags: ["executivo", "premium"],
            featured: true,
            isNew: false
        },
        {
            id: "caneta-eco-bamboo",
            name: "Caneta Eco Bamboo",
            code: "CA-4198",
            category: "canetas",
            image: "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1200&q=88",
            gallery: ["https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1200&q=88"],
            shortDescription: "Corpo em bambu e detalhes de acabamento natural.",
            description: "Uma alternativa com estética natural para campanhas relacionadas à sustentabilidade, educação e responsabilidade corporativa.",
            materials: "Bambu e metal",
            dimensions: "13,8 × 1,2 cm",
            colors: ["Natural"],
            personalization: "Laser ou silk",
            minQuantity: "A consultar",
            tags: ["ecológico", "lançamento"],
            featured: false,
            isNew: true
        },
        {
            id: "caderno-executivo-orbit",
            name: "Caderno Executivo Orbit A5",
            code: "CD-5014",
            category: "agendas-cadernos",
            image: "https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=1200&q=88",
            gallery: ["https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=1200&q=88"],
            shortDescription: "Capa rígida, elástico e acabamento sofisticado.",
            description: "Caderno de perfil executivo para reuniões, treinamentos e kits de onboarding. Possui ótimo espaço de marca na capa.",
            materials: "Papel e revestimento sintético",
            dimensions: "A5 · 14,5 × 21 cm",
            colors: ["Preto", "Azul-marinho", "Caramelo", "Verde"],
            personalization: "Silk, UV ou baixo-relevo",
            minQuantity: "A consultar",
            tags: ["onboarding", "escritório"],
            featured: true,
            isNew: false
        },
        {
            id: "agenda-planner-essencial",
            name: "Agenda Planner Essencial",
            code: "AG-5090",
            category: "agendas-cadernos",
            image: "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=1200&q=88",
            gallery: ["https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=1200&q=88"],
            shortDescription: "Organização semanal com visual limpo e funcional.",
            description: "Planner corporativo para apoiar organização, metas e rotina de equipes. A capa pode receber personalização da empresa ou campanha.",
            materials: "Papel certificado e capa rígida",
            dimensions: "17 × 24 cm",
            colors: ["Areia", "Preto", "Terracota"],
            personalization: "UV, silk ou hot stamping",
            minQuantity: "A consultar",
            tags: ["organização"],
            featured: false,
            isNew: false
        },
        {
            id: "mochila-executiva-nomad",
            name: "Mochila Executiva Nomad",
            code: "MO-6021",
            category: "bolsas-mochilas",
            image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1200&q=88",
            gallery: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1200&q=88"],
            shortDescription: "Compartimento para notebook e design urbano.",
            description: "Mochila corporativa com compartimentos organizadores e espaço para notebook, indicada para equipes, viagens e ações de reconhecimento.",
            materials: "Poliéster resistente",
            dimensions: "44 × 30 × 14 cm",
            colors: ["Preto", "Cinza", "Azul-marinho"],
            personalization: "Silk, bordado ou plaqueta",
            minQuantity: "A consultar",
            tags: ["premium", "viagem"],
            featured: true,
            isNew: false
        },
        {
            id: "bolsa-termica-day",
            name: "Bolsa Térmica Day 8 L",
            code: "BT-6084",
            category: "bolsas-mochilas",
            image: "https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=1200&q=88",
            gallery: ["https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=1200&q=88"],
            shortDescription: "Compacta, funcional e fácil de transportar.",
            description: "Bolsa térmica para ações de verão, alimentação e bem-estar. Possui alça confortável e área frontal para personalização.",
            materials: "Poliéster e revestimento térmico",
            dimensions: "25 × 21 × 15 cm",
            colors: ["Preto", "Azul", "Vermelho"],
            personalization: "Silk ou transfer",
            minQuantity: "A consultar",
            tags: ["dia a dia"],
            featured: false,
            isNew: true
        },
        {
            id: "carregador-wireless-loop",
            name: "Carregador Wireless Loop",
            code: "TC-7024",
            category: "tecnologia",
            image: "https://images.unsplash.com/photo-1586953208448-b95a79798f07?auto=format&fit=crop&w=1200&q=88",
            gallery: ["https://images.unsplash.com/photo-1586953208448-b95a79798f07?auto=format&fit=crop&w=1200&q=88"],
            shortDescription: "Carregamento por indução em base compacta.",
            description: "Acessório tecnológico para mesas de trabalho, kits executivos e campanhas de inovação. Compatibilidade sujeita ao modelo do aparelho.",
            materials: "ABS e componentes eletrônicos",
            dimensions: "9,8 × 9,8 × 0,9 cm",
            colors: ["Preto", "Branco"],
            personalization: "UV ou silk",
            minQuantity: "A consultar",
            tags: ["tecnologia", "lançamento"],
            featured: true,
            isNew: true
        },
        {
            id: "fone-bluetooth-pulse",
            name: "Fone Bluetooth Pulse",
            code: "TC-7092",
            category: "tecnologia",
            image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=88",
            gallery: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=88"],
            shortDescription: "Som sem fio e estojo compacto para transporte.",
            description: "Uma opção moderna para campanhas de relacionamento, premiações e kits de colaboradores. Consulte autonomia e compatibilidade.",
            materials: "ABS e componentes eletrônicos",
            dimensions: "Estojo compacto",
            colors: ["Preto", "Branco"],
            personalization: "UV no estojo",
            minQuantity: "A consultar",
            tags: ["tecnologia", "premium"],
            featured: false,
            isNew: false
        },
        {
            id: "kit-onboarding-welcome",
            name: "Kit Onboarding Welcome",
            code: "KT-8020",
            category: "kits-corporativos",
            image: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=1200&q=88",
            gallery: ["https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=1200&q=88"],
            shortDescription: "Composição personalizável para receber novos talentos.",
            description: "Kit demonstrativo que pode combinar caixa, caneca, caderno, caneta e cartão de boas-vindas. A composição final é definida conforme orçamento e campanha.",
            materials: "Composição variada",
            dimensions: "Personalizável",
            colors: ["Conforme identidade visual"],
            personalization: "Aplicação coordenada em todos os itens",
            minQuantity: "A consultar",
            tags: ["onboarding", "mais vendido"],
            featured: true,
            isNew: false
        },
        {
            id: "kit-cafe-experience",
            name: "Kit Café Experience",
            code: "KT-8075",
            category: "kits-corporativos",
            image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=88",
            gallery: ["https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=88"],
            shortDescription: "Experiência afetiva para clientes e equipes.",
            description: "Composição com caneca, café especial e embalagem personalizada. Ideal para datas comemorativas, relacionamento e reconhecimento.",
            materials: "Composição variada",
            dimensions: "Personalizável",
            colors: ["Conforme identidade visual"],
            personalization: "Caixa, tag, cartão e itens internos",
            minQuantity: "A consultar",
            tags: ["presente", "experiência"],
            featured: false,
            isNew: true
        },
        {
            id: "caderno-reciclado-raiz",
            name: "Caderno Reciclado Raiz",
            code: "EC-9018",
            category: "ecologicos",
            image: "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1200&q=88",
            gallery: ["https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1200&q=88"],
            shortDescription: "Papel reciclado e acabamento de estética natural.",
            description: "Caderno com visual orgânico para campanhas de sustentabilidade, treinamentos e eventos. Pode acompanhar caneta ecológica.",
            materials: "Papel reciclado",
            dimensions: "14 × 21 cm",
            colors: ["Kraft", "Natural"],
            personalization: "Silk ou gravação",
            minQuantity: "A consultar",
            tags: ["ecológico", "sustentabilidade"],
            featured: false,
            isNew: false
        },
        {
            id: "sacola-algodao-origem",
            name: "Sacola de Algodão Origem",
            code: "EC-9056",
            category: "ecologicos",
            image: "https://images.unsplash.com/photo-1597484662317-9bd7bdda2907?auto=format&fit=crop&w=1200&q=88",
            gallery: ["https://images.unsplash.com/photo-1597484662317-9bd7bdda2907?auto=format&fit=crop&w=1200&q=88"],
            shortDescription: "Reutilizável, leve e com ampla área de impressão.",
            description: "Sacola versátil para eventos, lojas, ações educativas e kits. O tecido natural oferece grande área para comunicação visual.",
            materials: "Algodão cru",
            dimensions: "38 × 42 cm",
            colors: ["Natural", "Preto"],
            personalization: "Silk ou transfer",
            minQuantity: "A consultar",
            tags: ["ecológico", "evento"],
            featured: false,
            isNew: false
        }
    ]
});
